COMPANY_NAME: "Chia Network Inc."
EXTRA_RUFF_CONFIG_SECTIONS: []
CGO_ENABLED: "0"
DEPENDABOT_DENY_LICENSES: "AGPL-1.0-only, AGPL-1.0-or-later, AGPL-1.0-or-later, AGPL-3.0-or-later, GPL-1.0-only, GPL-1.0-or-later, GPL-2.0-only, GPL-2.0-or-later, GPL-3.0-only, GPL-3.0-or-later"
DEPENDABOT_GOMOD_PULL_REQUEST_LIMIT: "10"
DEPENDABOT_GOMOD_REBASE_STRATEGY: "auto"
DEPENDABOT_GOMOD_DIRECTORY: "/"
DEPENDABOT_GOMOD_REVIEWERS: '["cmmarslender", "Starttoaster"]'
DEPENDABOT_GOMOD_GROUP_UPDATES: "1"
DEPENDABOT_PIP_PULL_REQUEST_LIMIT: "10"
DEPENDABOT_PIP_REBASE_STRATEGY: "auto"
DEPENDABOT_PIP_DIRECTORY: "/"
DEPENDABOT_PIP_REVIEWERS: '["emlowe"]'
DEPENDABOT_PIP_GROUP_UPDATES: "0"
DEPENDABOT_ACTIONS_PULL_REQUEST_LIMIT: "10"
DEPENDABOT_ACTIONS_REBASE_STRATEGY: "auto"
DEPENDABOT_ACTIONS_DIRECTORIES: '["/", ".github/actions/*"]'
DEPENDABOT_ACTIONS_REVIEWERS: '["cmmarslender", "Starttoaster", "pmaslana"]'
DEPENDABOT_ACTIONS_GROUP_UPDATES: "0"
DEPENDABOT_NPM_PULL_REQUEST_LIMIT: "10"
DEPENDABOT_NPM_REBASE_STRATEGY: "auto"
DEPENDABOT_NPM_DIRECTORY: "/"
DEPENDABOT_NPM_REVIEWERS: '["cmmarslender", "ChiaMineJP"]'
DEPENDABOT_NPM_GROUP_UPDATES: "0"
DEPENDABOT_CARGO_DIRECTORY: "/"
DEPENDABOT_CARGO_PULL_REQUEST_LIMIT: "10"
DEPENDABOT_CARGO_REBASE_STRATEGY: "auto"
DEPENDABOT_CARGO_GROUP_UPDATES: "0"
DEPENDENCY_REVIEW_ALLOW_DEPENDENCIES_LICENSES: pkg:pypi/pyinstaller
DEPENDABOT_SWIFT_DIRECTORY: "/"
DEPENDABOT_SWIFT_PULL_REQUEST_LIMIT: "10"
DEPENDABOT_SWIFT_REBASE_STRATEGY: "auto"
DEPENDABOT_SWIFT_GROUP_UPDATES: "0"
